'use client';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { DiffViewer, parseUnifiedDiff } from '@/components/system/code';
import { VerificationBadge } from '@/components/system/status';
import { PatchQualityBadge } from '@/components/findings/patch-quality-badge';
import { ProofOfFixPanel } from '@/components/findings/proof-of-fix';
import { VerificationSection } from '@/components/patch-verification';
import type { Patch } from '@/types/api';
import { Loader2, Shield, Wand2 } from 'lucide-react';

/**
 * PatchesPanel — candidate repairs and their proof-of-fix.
 *
 * Kept as its own component because "show me the diff" and "prove the diff
 * works" are a different task from reading the finding, and they are the only
 * part of the page that mutates state on the server.
 */
export function PatchesPanel({
  findingId,
  patches,
  loading,
  onGenerate,
  generating,
  generateError,
}: {
  findingId: string;
  patches?: Patch[];
  loading: boolean;
  onGenerate: () => void;
  generating: boolean;
  generateError?: string | null;
}) {
  return (
    <div className="space-y-5">
      <ProofOfFixPanel findingId={findingId} />

      <Card>
        <CardHeader className="flex flex-row items-center justify-between gap-3 space-y-0">
          <CardTitle className="text-base">Candidate patches</CardTitle>
          <Button size="sm" onClick={onGenerate} disabled={generating}>
            {generating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Wand2 className="mr-2 h-4 w-4" />}
            Generate fix
          </Button>
        </CardHeader>

        {generateError && (
          <div className="px-6 pb-2">
            <p className="rounded border border-destructive/20 bg-destructive/5 px-3 py-2 text-sm text-destructive">
              {generateError}
            </p>
          </div>
        )}

        <CardContent>
          {loading ? (
            <div className="space-y-4">
              {[1, 2].map((i) => (
                <div key={i} className="h-40 animate-pulse rounded-lg bg-muted" />
              ))}
            </div>
          ) : patches?.length === 0 ? (
            <div className="rounded-lg border border-dashed border-border/70 px-4 py-10 text-center">
              <Shield className="mx-auto mb-3 h-8 w-8 text-muted-foreground/50" aria-hidden="true" />
              <p className="text-sm font-medium">No patches generated</p>
              <p className="mx-auto mt-1 max-w-[52ch] text-xs leading-relaxed text-muted-foreground">
                Generate a candidate fix to see a reviewable diff. The patch is never applied to the
                original repository — verification runs on an isolated copy.
              </p>
            </div>
          ) : (
            <div className="space-y-5">
              {patches?.map((patch) => (
                <article key={patch.id} className="overflow-hidden rounded-lg border border-border/70">
                  <div className="flex flex-col gap-3 border-b border-border/60 bg-muted/40 p-4 sm:flex-row sm:items-center sm:justify-between">
                    <div className="flex items-center gap-3">
                      <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10 text-primary">
                        <Shield className="h-4 w-4" aria-hidden="true" />
                      </span>
                      <div>
                        <p className="mono-label">generated by {patch.generated_by}</p>
                        <p className="font-mono text-[11px] text-muted-foreground/70">
                          {patch.id.slice(0, 8)}
                        </p>
                      </div>
                    </div>
                    <div className="flex flex-wrap items-center gap-2 sm:justify-end">
                      <PatchQualityBadge patchId={patch.id} />
                      {patch.status === 'verified' ? (
                        <VerificationBadge decision="VERIFIED_FIX" />
                      ) : patch.status === 'failed' ? (
                        <VerificationBadge decision="REJECTED_FIX" />
                      ) : (
                        <span className="chip state-probable-soft">
                          {patch.status === 'applied' ? 'Applied — awaiting verification' : 'Candidate'}
                        </span>
                      )}
                    </div>
                  </div>

                  {patch.explanation && (
                    <p className="border-b border-border/60 bg-muted/20 px-4 py-2.5 text-[13px] text-muted-foreground">
                      {patch.explanation}
                    </p>
                  )}

                  <div className="space-y-2 p-4">
                    <p className="mono-label">Proposed diff — review before trusting</p>
                    <DiffViewer lines={parseUnifiedDiff(patch.diff)} />
                  </div>

                  <VerificationSection patch={patch} />
                </article>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
