"""align schema with models

Revision ID: 4d3b145e76e1
Revises: 006
Create Date: 2026-09-17 20:23:09.150740

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.db.base  # noqa: F401  # registers GUID type for autogenerate
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d3b145e76e1"
down_revision = "006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Enums that older String-typed columns must now be altered to, or that
    # new columns reference, may not exist yet on databases provisioned from
    # the earlier migrations. Create them idempotently before any DDL runs.
    for name, values in (
        ("org_role", ("member", "admin", "owner")),
        ("plan_name", ("free", "pro", "team")),
        ("subscription_status", ("active", "trialing", "past_due", "canceled", "incomplete")),
    ):
        joined = ", ".join(f"'{v}'" for v in values)
        op.execute(
            f"""DO $$ BEGIN
                   CREATE TYPE {name} AS ENUM ({joined});
               EXCEPTION
                   WHEN duplicate_object THEN NULL;
               END $$;"""
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_accounts",
        sa.Column("user_id", app.db.base.GUID(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("provider_email", sa.String(length=320), nullable=True),
        sa.Column("provider_name", sa.String(length=200), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider", name="uq_oauth_user_provider"),
    )
    op.create_index(op.f("ix_oauth_accounts_user_id"), "oauth_accounts", ["user_id"], unique=False)
    op.create_table(
        "change_audits",
        sa.Column("repository_id", app.db.base.GUID(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("base", sa.String(length=200), nullable=True),
        sa.Column("head", sa.String(length=200), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_change_audits_repository_id"), "change_audits", ["repository_id"], unique=False)
    op.create_table(
        "health_snapshots",
        sa.Column("repository_id", app.db.base.GUID(), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("average_score", sa.Float(), nullable=True),
        sa.Column("files_scored", sa.Integer(), nullable=False),
        sa.Column("distribution", sa.JSON(), nullable=True),
        sa.Column("worst_files", sa.JSON(), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "commit_sha", name="uq_health_snapshot_repo_commit"),
    )
    op.create_index(
        op.f("ix_health_snapshots_repository_id"), "health_snapshots", ["repository_id"], unique=False
    )
    op.create_table(
        "pull_request_audits",
        sa.Column("repository_id", app.db.base.GUID(), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=False),
        sa.Column("pr_title", sa.String(length=500), nullable=True),
        sa.Column("pr_url", sa.String(length=2048), nullable=True),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("base_ref", sa.String(length=200), nullable=True),
        sa.Column("base_sha", sa.String(length=64), nullable=True),
        sa.Column("head_ref", sa.String(length=200), nullable=True),
        sa.Column("head_sha", sa.String(length=64), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("changed_files", sa.JSON(), nullable=False),
        sa.Column("findings", sa.JSON(), nullable=False),
        sa.Column("review", sa.JSON(), nullable=False),
        sa.Column("posted", sa.Boolean(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "pr_number", name="uq_pr_audit_repo_pr"),
    )
    op.create_index(
        op.f("ix_pull_request_audits_repository_id"), "pull_request_audits", ["repository_id"], unique=False
    )
    op.create_table(
        "repository_insights",
        sa.Column("repository_id", app.db.base.GUID(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("health", sa.JSON(), nullable=True),
        sa.Column("git", sa.JSON(), nullable=True),
        sa.Column("wiki", sa.JSON(), nullable=True),
        sa.Column("architecture", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_repository_insights_repository_id"), "repository_insights", ["repository_id"], unique=True
    )
    op.create_table(
        "generated_tests",
        sa.Column("finding_id", app.db.base.GUID(), nullable=False),
        sa.Column("language", sa.String(length=30), nullable=False),
        sa.Column("test_code", sa.Text(), nullable=False),
        sa.Column("generated_by", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_generated_tests_finding_id"), "generated_tests", ["finding_id"], unique=False)
    op.create_table(
        "validation_runs",
        sa.Column("finding_id", app.db.base.GUID(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("rule", sa.String(length=100), nullable=True),
        sa.Column("status_before", sa.String(length=20), nullable=False),
        sa.Column("status_after", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("checks", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_validation_runs_finding_id"), "validation_runs", ["finding_id"], unique=False)
    op.alter_column(
        "analysis_runs",
        "output",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.create_index("ix_analysis_runs_scan_stage", "analysis_runs", ["scan_id", "stage"], unique=False)
    op.alter_column(
        "auth_events",
        "detail",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "dependencies",
        "vulnerability_info",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "evidence",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.create_index("ix_evidence_finding_order", "evidence", ["finding_id", "order_index"], unique=False)
    op.create_index("ix_findings_scan_file", "findings", ["scan_id", "file_path"], unique=False)
    op.create_index(
        "ix_findings_scan_severity_status", "findings", ["scan_id", "severity", "status"], unique=False
    )
    op.execute("ALTER TABLE organization_members ALTER COLUMN role DROP DEFAULT")
    op.execute("ALTER TABLE organization_members ALTER COLUMN role TYPE org_role USING role::org_role")
    # The ORM supplies the role default in Python (OrgRole.member); the
    # column intentionally keeps no server default (matches the models).
    op.alter_column(
        "processed_auth_webhooks",
        "provider",
        existing_type=sa.VARCHAR(length=30),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "processed_auth_webhooks",
        "received_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "report_shares",
        "view_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column("repositories", sa.Column("oauth_account_id", app.db.base.GUID(), nullable=True))
    op.alter_column(
        "repositories",
        "primary_languages",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        None, "repositories", "oauth_accounts", ["oauth_account_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("scans", sa.Column("idempotency_key", sa.String(length=128), nullable=True))
    op.alter_column(
        "scans",
        "summary",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "scans",
        "llm_token_usage",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_scans_idempotency_key"), "scans", ["idempotency_key"], unique=False)
    op.create_index("ix_scans_repository_created", "scans", ["repository_id", "created_at"], unique=False)
    op.alter_column(
        "symbols",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.add_column(
        "users", sa.Column("plan", sa.Enum("free", "pro", "team", name="plan_name"), nullable=False)
    )
    op.add_column(
        "users",
        sa.Column(
            "subscription_status",
            sa.Enum("active", "trialing", "past_due", "canceled", "incomplete", name="subscription_status"),
            nullable=True,
        ),
    )
    op.add_column("users", sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("stripe_customer_id", sa.String(length=200), nullable=True))
    op.add_column("users", sa.Column("stripe_subscription_id", sa.String(length=200), nullable=True))
    op.add_column("users", sa.Column("scans_used", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("fixes_used", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("verifications_used", sa.Integer(), nullable=False))
    op.alter_column(
        "users",
        "status",
        existing_type=postgresql.ENUM(
            "active", "email_unverified", "suspended", "deleted", name="user_status"
        ),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "failed_login_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users", "token_version", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
    )
    op.create_index(op.f("ix_users_stripe_customer_id"), "users", ["stripe_customer_id"], unique=False)
    op.alter_column(
        "website_audits",
        "status",
        existing_type=sa.VARCHAR(length=30),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "website_audits",
        "max_pages",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "website_audits",
        "max_depth",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "website_audits",
        "pages_crawled",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "website_audits",
        "scores",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "website_audits",
        "summary",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "website_audits",
        "pages",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "website_audits",
        "findings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "website_audits",
        "evidence",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "websites",
        "status",
        existing_type=sa.VARCHAR(length=30),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "websites",
        "status",
        existing_type=sa.VARCHAR(length=30),
        server_default=sa.text("'active'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "website_audits",
        "evidence",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "website_audits",
        "findings",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "website_audits",
        "pages",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "website_audits",
        "summary",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "website_audits",
        "scores",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "website_audits",
        "pages_crawled",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "website_audits",
        "max_depth",
        existing_type=sa.INTEGER(),
        server_default=sa.text("2"),
        existing_nullable=False,
    )
    op.alter_column(
        "website_audits",
        "max_pages",
        existing_type=sa.INTEGER(),
        server_default=sa.text("10"),
        existing_nullable=False,
    )
    op.alter_column(
        "website_audits",
        "status",
        existing_type=sa.VARCHAR(length=30),
        server_default=sa.text("'pending'::character varying"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_users_stripe_customer_id"), table_name="users")
    op.alter_column(
        "users",
        "token_version",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "failed_login_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "status",
        existing_type=postgresql.ENUM(
            "active", "email_unverified", "suspended", "deleted", name="user_status"
        ),
        server_default=sa.text("'active'::user_status"),
        existing_nullable=False,
    )
    op.drop_column("users", "verifications_used")
    op.drop_column("users", "fixes_used")
    op.drop_column("users", "scans_used")
    op.drop_column("users", "stripe_subscription_id")
    op.drop_column("users", "stripe_customer_id")
    op.drop_column("users", "current_period_end")
    op.drop_column("users", "subscription_status")
    op.drop_column("users", "plan")
    op.alter_column(
        "symbols",
        "metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_index("ix_scans_repository_created", table_name="scans")
    op.drop_index(op.f("ix_scans_idempotency_key"), table_name="scans")
    op.alter_column(
        "scans",
        "llm_token_usage",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "scans",
        "summary",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_column("scans", "idempotency_key")
    op.drop_constraint(None, "repositories", type_="foreignkey")
    op.alter_column(
        "repositories",
        "primary_languages",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_column("repositories", "oauth_account_id")
    op.alter_column(
        "report_shares",
        "view_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "processed_auth_webhooks",
        "received_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "processed_auth_webhooks",
        "provider",
        existing_type=sa.VARCHAR(length=30),
        server_default=sa.text("'repoverix-local'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "organization_members",
        "role",
        existing_type=sa.Enum("member", "admin", "owner", name="org_role"),
        server_default=sa.text("'member'::character varying"),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.drop_index("ix_findings_scan_severity_status", table_name="findings")
    op.drop_index("ix_findings_scan_file", table_name="findings")
    op.drop_index("ix_evidence_finding_order", table_name="evidence")
    op.alter_column(
        "evidence",
        "metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "dependencies",
        "vulnerability_info",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "auth_events",
        "detail",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index("ix_analysis_runs_scan_stage", table_name="analysis_runs")
    op.alter_column(
        "analysis_runs",
        "output",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_validation_runs_finding_id"), table_name="validation_runs")
    op.drop_table("validation_runs")
    op.drop_index(op.f("ix_generated_tests_finding_id"), table_name="generated_tests")
    op.drop_table("generated_tests")
    op.drop_index(op.f("ix_repository_insights_repository_id"), table_name="repository_insights")
    op.drop_table("repository_insights")
    op.drop_index(op.f("ix_pull_request_audits_repository_id"), table_name="pull_request_audits")
    op.drop_table("pull_request_audits")
    op.drop_index(op.f("ix_health_snapshots_repository_id"), table_name="health_snapshots")
    op.drop_table("health_snapshots")
    op.drop_index(op.f("ix_change_audits_repository_id"), table_name="change_audits")
    op.drop_table("change_audits")
    op.drop_index(op.f("ix_oauth_accounts_user_id"), table_name="oauth_accounts")
    op.drop_table("oauth_accounts")
    # ### end Alembic commands ###
