"""Automated regression-test generation for findings.

A generated test is a *contract assertion*: it reads the finding's source file
and asserts the absence of the vulnerable pattern. It therefore FAILS on the
vulnerable code (demonstrating the defect) and PASSES once a correct fix
removes the pattern — a true regression test that needs no app runtime,
fixtures or network. LLM mode (when a provider key is configured) writes a
behavioral test that calls the function with an attack payload and asserts the
safe outcome instead.
"""

from __future__ import annotations

import re
import shutil
import tempfile
from pathlib import Path

from app.analysis.models import AnalysisError, LLMUsage
from app.db.models import Finding

_RULE_PATTERNS: dict[str, re.Pattern] = {
    "RVX-SQLI-001": re.compile(
        r"(execute|executemany|query)\s*\(\s*f[\"']|query\s*=\s*f[\"']",
        re.IGNORECASE,
    ),
    "RVX-SQLI-JS-001": re.compile(r"\.(query|execute)\s*\(\s*(`|\$)", re.IGNORECASE),
    "RVX-CMDI-001": re.compile(r"shell\s*=\s*True|(os\.)?(system|popen)\s*\(", re.IGNORECASE),
    "RVX-CMDI-JS-001": re.compile(r"child_process\.[a-z]+\(|exec\s*\(\s*`", re.IGNORECASE),
    "RVX-EVAL-001": re.compile(r"\beval\s*\(|\bexec\s*\(", re.IGNORECASE),
    "RVX-EVAL-JS-001": re.compile(r"\beval\s*\(|new\s+Function\s*\(", re.IGNORECASE),
    "RVX-SECRET-001": re.compile(
        r"(api[_-]?key|secret|token|password)\s*=\s*[\"'][A-Za-z0-9]{12,}[\"']", re.IGNORECASE
    ),
    "RVX-SECRET-002": re.compile(
        r"(api[_-]?key|secret|token|password)\s*[:=]\s*[\"'][A-Za-z0-9]{12,}[\"']", re.IGNORECASE
    ),
    "RVX-SECRET-JS-001": re.compile(
        r"(api[_-]?key|secret|token|password)\s*[:=]\s*[\"'][A-Za-z0-9]{12,}[\"']", re.IGNORECASE
    ),
    "RVX-CRYPTO-001": re.compile(r"\bmd5\b|\bsha1\b", re.IGNORECASE),
}

_RULE_LABELS = {
    "RVX-SQLI-001": "SQL string interpolation",
    "RVX-SQLI-JS-001": "SQL string interpolation",
    "RVX-CMDI-001": "shell execution with dynamic input",
    "RVX-CMDI-JS-001": "shell execution with dynamic input",
    "RVX-EVAL-001": "dynamic code evaluation",
    "RVX-EVAL-JS-001": "dynamic code evaluation",
    "RVX-SECRET-001": "hardcoded credential",
    "RVX-SECRET-002": "hardcoded credential",
    "RVX-SECRET-JS-001": "hardcoded credential",
    "RVX-CRYPTO-001": "weak cryptographic hash",
}


def finding_rule(finding: Finding) -> str:
    extra = finding.evidence[0].extra if finding.evidence and finding.evidence[0].extra else {}
    return str(extra.get("rule") or "")


def template_test(finding: Finding) -> tuple[str, str] | None:
    """Deterministic contract test for a finding; returns (filename, code)."""
    rule = finding_rule(finding)
    pattern = _RULE_PATTERNS.get(rule)
    if pattern is None:
        return None
    label = _RULE_LABELS.get(rule, rule)
    file_path = finding.file_path
    stem = file_path.rsplit("/", 1)[-1].rsplit(".", 1)[0]
    filename = f"test_gen_{stem}_{rule.lower().replace('-', '_')}.py"
    rel = ", ".join(repr(part) for part in file_path.split("/"))
    code = f'''"""Regression test generated by RepoVeriX for finding {finding.external_id}.

Contract: {label} must not appear in {file_path}.
This test FAILS on the vulnerable code (demonstrating the defect) and PASSES
after a fix removes the pattern. Generated deterministically — no runtime,
fixtures or network required.
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

SOURCE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", *[{rel}])
PATTERN = {pattern.pattern!r}


def test_no_{stem}_vulnerable_pattern():
    with open(SOURCE, encoding="utf-8", errors="replace") as handle:
        source = handle.read()
    matches = re.findall(PATTERN, source, re.IGNORECASE)
    assert not matches, f"Vulnerable pattern still present in {{SOURCE}}: {{matches}}"
'''
    return filename, code


async def llm_test(finding: Finding, source_root: Path, provider, usage: LLMUsage) -> tuple[str, str]:
    """LLM-written behavioral test (needs a configured provider)."""
    from app.analysis.llm import complete_json, load_prompt

    file_path = finding.file_path
    full = source_root / file_path
    if not full.is_file():
        raise AnalysisError(f"Source file missing: {file_path}", code="source_missing")
    source = full.read_text(encoding="utf-8", errors="replace")
    snippet_lines = source.splitlines()
    lo = max(0, (finding.line_start or 1) - 1 - 6)
    hi = min(len(snippet_lines), (finding.line_end or finding.line_start or 1) + 6)
    snippet = "\n".join(f"{i + 1:>5} | {snippet_lines[i]}" for i in range(lo, hi))

    stem = file_path.rsplit("/", 1)[-1].rsplit(".", 1)[0]
    ext = file_path.rsplit(".", 1)[-1]
    framework = "pytest" if ext == "py" else "jest"

    system = load_prompt("system_security")
    template = load_prompt("test_generation")
    user = template.format(
        file_path=file_path,
        title=finding.title,
        description=finding.description[:800],
        snippet=snippet,
        framework=framework,
    )
    data = await complete_json(provider, system, user, usage)
    code = str(data.get("test_code") or data.get("content") or "")
    if not code.strip():
        raise AnalysisError("LLM returned no test code", code="llm_empty")
    filename = f"test_gen_{stem}_{finding.external_id[:8]}.{ext if ext in ('py',) else 'test.' + ext}"
    if ext != "py":
        filename = f"test_gen_{stem}_{finding.external_id[:8]}.test.{ext}"
    return filename, code


def _classify_outcome(passed: bool, returncode: int, tests: list[dict]) -> tuple[str, str]:
    """Map a run onto the reproduction-test taxonomy.

    TEST_REPRODUCES_BUG      the test failed on an assertion -> the suspected
                             defect was demonstrated on this code.
    TEST_DOES_NOT_REPRODUCE  the test passed -> the defect is not present here.
    TEST_FAILED_TO_EXECUTE   the environment prevented meaningful execution
                             (infrastructure / collection error), which is NOT
                             evidence about the defect either way.
    """
    if passed:
        return "TEST_DOES_NOT_REPRODUCE", "test passed — suspected defect not present on this code"
    if not tests:
        return (
            "TEST_FAILED_TO_EXECUTE",
            "no test results — infrastructure or collection failure, not a defect signal",
        )
    failures = [t for t in tests if t["outcome"] == "failed"]
    errors = [t for t in tests if t["outcome"] == "error"]
    if failures and not errors:
        return "TEST_REPRODUCES_BUG", f"test assertion failed ({len(failures)} test(s)) — defect demonstrated"
    return "TEST_FAILED_TO_EXECUTE", "test errored during setup/collection — not a defect signal"


async def run_generated_test(
    source_root: Path,
    test_filename: str,
    test_code: str,
    *,
    runner=None,
    timeout_seconds: int = 300,
    patch_diff: str | None = None,
) -> dict:
    """Copy the working copy, drop the test in, and execute it in isolation.

    When ``patch_diff`` is given it is applied to the isolated copy *before*
    the run, so the same reproduction test can be executed against the patched
    version (the Proof-of-Fix half of the comparison).
    """
    from app.analysis.patchops import PatchError, apply_patch_to_directory
    from app.analysis.process import run_command
    from app.analysis.verify import DockerRunner, LocalRunner, _parse_junit

    workdir = Path(tempfile.mkdtemp(prefix="repoverix-testgen-"))
    try:
        shutil.copytree(
            source_root,
            workdir / "src",
            ignore=shutil.ignore_patterns(".git", "__pycache__", ".pytest_cache"),
        )
        src = workdir / "src"
        tests_dir = src / "tests"
        tests_dir.mkdir(exist_ok=True)
        (tests_dir / test_filename).write_text(test_code, encoding="utf-8")

        patched_files: list[str] = []
        if patch_diff:
            try:
                patched_files = apply_patch_to_directory(src, patch_diff)
            except PatchError as exc:
                return {
                    "runner": "patch",
                    "passed": False,
                    "patch_applied": False,
                    "patch_error": exc.message,
                    "outcome": "TEST_FAILED_TO_EXECUTE",
                    "outcome_detail": f"candidate patch could not be applied: {exc.message}",
                    "summary": exc.message[:2000],
                    "tests": [],
                }

        if runner is None:
            docker_runner = DockerRunner()
            if await docker_runner._docker_available():
                runner_instance = docker_runner
            else:
                # Docker absent -> controlled subprocess sandbox with the same
                # decision logic (see docs/verification.md).
                runner_instance = LocalRunner()
        else:
            runner_instance = runner
        if isinstance(runner_instance, LocalRunner):
            result = await run_command(
                [
                    runner_instance.python,
                    "-m",
                    "pytest",
                    "-q",
                    f"tests/{test_filename}",
                    "--junitxml=junit.xml",
                ],
                cwd=src,
                timeout_seconds=timeout_seconds,
                env_extra={"PYTHONDONTWRITEBYTECODE": "1"},
            )
            tests = _parse_junit(src / "junit.xml")
            passed = result.returncode == 0
            outcome, outcome_detail = _classify_outcome(passed, result.returncode, tests)
            return {
                "runner": "local-test",
                "passed": passed,
                "patch_applied": bool(patched_files),
                "patched_files": patched_files,
                "outcome": outcome,
                "outcome_detail": outcome_detail,
                "summary": (result.stdout + result.stderr)[-4000:],
                "tests": tests,
            }

        # Docker path: run only the generated test file
        from app.core.config import get_settings

        settings = get_settings()
        host = str(src.resolve())
        command = (
            "python -m pip install -q --disable-pip-version-check pytest || true "
            f"&& pytest -q tests/{test_filename} --junitxml=/workspace/junit.xml"
        )
        args = [
            "docker",
            "run",
            "--rm",
            "--network",
            settings.sandbox_network,
            "-m",
            settings.sandbox_memory_limit,
            "--cpus",
            str(settings.sandbox_cpu_limit),
            "-v",
            f"{host}:/workspace",
            "-w",
            "/workspace",
            "-e",
            "PYTHONUNBUFFERED=1",
            "-i",
            "python:3.12-slim",
            "sh",
            "-c",
            command,
        ]
        try:
            result = await run_command(args, timeout_seconds=timeout_seconds)
        except (FileNotFoundError, TimeoutError) as exc:
            return {
                "runner": "docker",
                "passed": False,
                "patch_applied": bool(patched_files),
                "patched_files": patched_files,
                "outcome": "TEST_FAILED_TO_EXECUTE",
                "outcome_detail": f"sandbox could not execute the test: {str(exc)[:300]}",
                "summary": str(exc)[:2000],
                "tests": [],
            }
        tests = _parse_junit(src / "junit.xml")
        outcome, outcome_detail = _classify_outcome(result.returncode == 0, result.returncode, tests)
        return {
            "runner": "docker",
            "passed": result.returncode == 0,
            "patch_applied": bool(patched_files),
            "patched_files": patched_files,
            "outcome": outcome,
            "outcome_detail": outcome_detail,
            "summary": (result.stdout + result.stderr)[-4000:],
            "tests": tests,
        }
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


async def generate_test(
    finding: Finding,
    source_root: Path,
    *,
    provider=None,
    usage: LLMUsage | None = None,
) -> dict:
    """Generate a regression test: deterministic contract test, or LLM upgrade.

    Returns ``{"filename", "code", "generated_by"}``.
    """
    template = template_test(finding)
    if template is not None:
        filename, code = template
        return {"filename": filename, "code": code, "generated_by": "repoverix-template"}

    if provider is None:
        raise AnalysisError(
            "No template exists for this finding's rule and no LLM provider is configured "
            "(set REPOVERIX_OPENAI_API_KEY / REPOVERIX_ANTHROPIC_API_KEY / REPOVERIX_GEMINI_API_KEY)",
            code="llm_unconfigured",
        )
    filename, code = await llm_test(finding, source_root, provider, usage or LLMUsage())
    return {"filename": filename, "code": code, "generated_by": "llm"}
